services:
  accounts:
    image: kushanxp/accounts:s4
    container_name: accounts_ms
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 750m
    networks:
      - micro_network
  loans:
    image: kushanxp/loans:s4
    container_name: loans_ms
    ports:
      - 8090:8090
    deploy:
      resources:
        limits:
          memory: 750m
    networks:
      - micro_network
  cards:
    image: kushanxp/cards:s4
    container_name: cards_ms
    ports:
      - 9000:9000
    deploy:
      resources:
        limits:
          memory: 750m
    networks:
      - micro_network

networks:
  micro_network:
    driver: bridge
