services:
  rabbitmq:
    user: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:4.0-management
    container_name: rabbitmq_ms
    ports:
      - 5672:5672
      - 15672:15672
    extends:
      file: common-config.yml
      service: network-deploy-service
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 5

  configserver:
    image: kushanxp/configserver:s6
    container_name: configserver_ms
    ports:
      - 8071:8071
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8071/actuator/health/readiness | grep "UP" || exit 1
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 5
    extends:
      file: common-config.yml
      service: microservices-base-config

  accounts:
    image: kushanxp/accounts:s6
    container_name: accounts_ms
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service: microservices-configserver-config

  loans:
    image: kushanxp/loans:s6
    container_name: loans_ms
    ports:
      - 8090:8090
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservices-configserver-config

  cards:
    image: kushanxp/cards:s6
    container_name: cards_ms
    ports:
      - 9000:9000
    environment:
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service: microservices-configserver-config

networks:
  micro_network:
    driver: bridge
